### ISSUE TITLE
Add whitespace indentation?

### ISSUE THREAD

**Issue by frontendinstructor** [stuffedmice/class#1]
Good job so far!

A few improvements:
1. Can you add indentation to your `homepage.html`: https://github.com/stuffedmice/class/blob/master/homepage.html ?
2. Can you make sure that link will get opened in a new tab: https://github.com/stuffedmice/class/blob/master/homepage.html#L11 ?

Ask any questions during today's class!

**Comment by stuffedmice** [comment]
all done
